(function(){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>'Gs. '+(Number(n)||0).toLocaleString('es-PY');
 const code=r=>Number(r?.numero_orden)>0?'RIT'+String(r.numero_orden).padStart(5,'0'):'';
 const total=r=>(Number(r.total_productos)||0)+(Number(r.costo_delivery)||0);
 const paid=r=>/^pagado$/i.test(r.estado_pago||'')?total(r):(Number(r.monto_pagado)||0);
 const balance=r=>Math.max(0,total(r)-paid(r));
 const date=v=>{if(!v)return'A coordinar';const d=new Date(String(v).slice(0,10)+'T12:00:00');return isNaN(d)?'A coordinar':d.toLocaleDateString('es-PY',{day:'numeric',month:'long',year:'numeric'});};
 function state(r){
  if(r.estado_entrega==='Cancelado')return'Cancelado';
  if(r.estado_entrega==='Entregado')return'Entregado';
  if(r.estado_entrega==='En camino')return'En camino';
  if(r.preparacion_estado==='Listo')return'Listo';
  if(r.preparacion_estado==='Preparando')return'Preparando';
  return'Recibido';
 }
 function items(r){
  if(Array.isArray(r.pedido_items)&&r.pedido_items.length)return r.pedido_items;
  return String(r.detalle||'').split(/\s*(?:,|·)\s*/).filter(Boolean).map(s=>{const m=s.match(/^(.*?)\s+[x×](\d+(?:\.\d+)?)$/i);return{nombre:m?m[1]:s,cant:m?Number(m[2]):1};});
 }
 function timeline(r){
  const s=state(r),labels=['Recibido','Preparando','Listo',...(s==='En camino'||/delivery|transport|uber/i.test(r.tipo_envio||'')?['En camino']:[]),'Entregado'];
  const current=labels.indexOf(s),stopped=s==='Cancelado';
  return `<section class="rp-card"><h2>Estado de tu pedido</h2>${stopped?'<div class="rp-notice error">Pedido cancelado. Contactá con Ritual Ancestral si necesitás ayuda.</div>':r.estado_entrega==='Reprogramado'?'<div class="rp-notice">La entrega fue reprogramada. Revisá la fecha acordada más abajo.</div>':''}<ol class="rp-timeline" aria-label="Seguimiento del pedido">${labels.map((l,i)=>`<li class="rp-step ${!stopped&&i<=current?'done':''} ${!stopped&&i===current&&s!=='Entregado'?'current':''}" ${i===current?'aria-current="step"':''}><span class="rp-dot" aria-hidden="true">${!stopped&&i<=current?'✓':''}</span>${l}</li>`).join('')}</ol></section>`;
 }
 const boxIcon='<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m12 3 9 5v8l-9 5-9-5V8zM3 8l9 5 9-5M12 13v8M7.5 5.5l9 5"/></svg>';
 function products(r){return `<h2>Productos <span style="font-weight:400;color:var(--rp-muted)">${items(r).reduce((a,x)=>a+(Number(x.cant)||0),0)}</span></h2><ul class="rp-items">${items(r).map(x=>`<li class="rp-item"><span class="rp-item-icon">${boxIcon}</span><div><div class="rp-item-name">${esc(x.nombre)}</div><small>${x.precio!=null?money(x.precio)+' × ': 'Cantidad: '}${esc(x.cant)}</small></div>${x.precio!=null?`<strong class="rp-item-price">${money(x.precio*x.cant)}</strong>`:''}</li>`).join('')||'<li>Sin detalle de productos</li>'}</ul>`;}
 function amounts(r){return `<hr class="rp-divider"><div class="rp-line"><span>Productos${Number(r.descuento)>0?' (descuento incluido)':''}</span><strong>${money(r.total_productos)}</strong></div><div class="rp-line"><span>${/retiro/i.test(r.tipo_envio||'')?'Retiro en el local':'Envío'}</span><strong>${money(r.costo_delivery)}</strong></div><div class="rp-line rp-total"><span>Total</span><strong>${money(total(r))}</strong></div><div class="rp-line"><span>Abonado</span><strong>${money(paid(r))}</strong></div><div class="rp-line rp-balance"><span>Saldo pendiente</span><strong>${money(balance(r))}</strong></div>`;}
 function details(r,admin){return `<div class="rp-grid"><div><small>Cliente</small><strong>${esc(r.cliente||'—')}</strong></div>${admin?`<div><small>Teléfono</small><strong>${esc(r.contacto||'—')}</strong></div><div><small>CI / RUC</small><strong>${esc(r.ruc||'—')}</strong></div>`:''}<div><small>Forma de pago</small><strong>${esc(r.metodo_pago||'A confirmar')}</strong></div><div><small>Pago</small><strong>${esc(r.estado_pago||'Pendiente')}</strong></div><div><small>Forma de entrega</small><strong>${esc(r.tipo_envio||'A confirmar')}</strong></div><div><small>Fecha de entrega</small><strong>${date(r.dia_entrega)}</strong></div>${admin?`<div class="rp-wide"><small>Dirección / referencia</small><strong>${esc(r.direccion_referencia||r.ciudad||'A confirmar')}</strong></div>`:''}</div>`;}
 function customer(r){return timeline(r)+`<section class="rp-card"><div class="rp-brand"><img src="pedido-logo.svg" alt="Ritual Ancestral"><div><strong>Ritual Ancestral</strong><small>Seguimiento de tu compra</small></div></div><div class="rp-order-id">Pedido #${esc(code(r))}</div><div class="rp-date">Realizado el ${date(r.fecha)}</div><hr class="rp-divider">${products(r)}${amounts(r)}<hr class="rp-divider"><h2>Detalles</h2>${details(r,false)}</section><div class="rp-footer">Ritual Ancestral · Enlace privado, no lo compartas públicamente.</div>`;}
 function admin(r,demo=false){
  return `<div class="rp-header"><div><div class="rp-heading-row"><h1 id="rpTitle">Pedido ${code(r)?'#'+esc(code(r)):'sin numeración'}</h1><span class="rp-tag" data-state="${state(r)}">${state(r)}</span></div><p>${date(r.fecha)} · ${esc(r.cliente||'')}</p></div><div class="rp-actions rp-no-print"><button class="rp-btn" data-rp="print">Imprimir</button>${/transport/i.test(r.tipo_envio||'')?`<button class="rp-btn" data-rp="shipping" ${demo?'disabled':''}>Ficha de envío</button>`:''}<button class="rp-btn" data-rp="edit" ${demo?'disabled':''}>Editar pedido</button></div></div><div class="rp-columns"><div><section class="rp-card">${products(r)}${amounts(r)}</section></div><div><section class="rp-card"><h2>Cliente, pago y entrega</h2>${details(r,true)}</section><section class="rp-card rp-no-print"><h2>Preparación del pedido</h2><div class="rp-actions"><select id="rpPreparation" aria-label="Estado de preparación">${['Recibido','Preparando','Listo'].map(s=>`<option value="${s==='Recibido'?'Nuevo':s}" ${(r.preparacion_estado===s||s==='Recibido'&&!['Preparando','Listo'].includes(r.preparacion_estado))?'selected':''}>${s}</option>`).join('')}</select><button class="rp-btn primary" data-rp="save" ${demo?'disabled':''}>Guardar estado</button></div><p>La entrega se actualiza desde sus controles habituales.</p></section><section class="rp-card rp-no-print"><h2>Seguimiento del cliente</h2><p>El cliente sólo verá el resumen y el estado de este pedido.</p><div class="rp-actions" style="margin-top:14px"><button class="rp-btn primary" data-rp="notify" ${demo?'disabled':''}>Avisar por WhatsApp</button><button class="rp-btn" data-rp="copy" ${demo?'disabled':''}>Copiar enlace</button><button class="rp-btn" data-rp="customer" ${demo?'disabled':''}>Ver como cliente</button><button class="rp-btn danger" data-rp="revoke" ${demo?'disabled':''}>Revocar enlace</button></div><p id="rpFeedback" role="status" style="margin-top:12px"></p></section></div></div>`;
 }
 const demo={id:'demo',numero_orden:59,fecha:'2026-09-03',cliente:'Cliente de ejemplo',contacto:'—',ruc:'—',detalle:'Yerbero Ritual Azul Marino x1, Kit Matero x1',total_productos:169000,costo_delivery:25000,monto_pagado:100000,estado_pago:'Parcial',preparacion_estado:'Preparando',estado_entrega:'Pendiente',tipo_envio:'Delivery',dia_entrega:'2026-09-05',metodo_pago:'Transferencia',pedido_items:[{nombre:'Yerbero Ritual Azul Marino',cant:1,precio:59000},{nombre:'Kit Matero',cant:1,precio:110000}]};
 window.RitualPedidos={esc,money,code,total,balance,date,state,items,timeline,customer,admin,demo};
})();
